### ISSUE TITLE
Relative Path to local file

### ISSUE THREAD

**Issue by madsel** [dlevs/vscode-pattern-links#5]
I have a project specific vscode setting file. myproject/.vscode/setting.json
In this file I would like to specify a relative link to a local file like this:

    "patternlinks.rules": [
        {
            "linkPattern": "MyPattern",
            "linkTarget": "file://../folder/MyPattern.m"
        }
]
Unfortunately, pattern-links expect the file to be found here C:/folder/MyPattern.m
Is there a way to use relative paths? Seems ${workspaceFolder} is not supported.

**Comment by dlevs** [comment]
Hey, this isn't supported in this project, but I made a successor to this extension that _does_ support `${workspaceFolder}`: https://github.com/dlevs/vscode-regex-robin

That should do exactly what you need!

**Comment by ylazy** [comment]
@dlevs Hi! Could you consider to support [others variables](https://code.visualstudio.com/docs/editor/variables-reference) like `${file}` so we can use something like this: `"linkTarget": "${file}/docs/$1.md"`?

When I do that:

![image](https://github.com/dlevs/vscode-pattern-links/assets/6010183/22ff1d84-55b5-47b6-b143-bf8c00cfdca7)

![image](https://github.com/dlevs/vscode-pattern-links/assets/6010183/3da81366-6c38-4da6-966a-3c974493f177)

My setting:
```json
"regexrobin.rules":
	[
		{
			"regex": "@component\\s+(\\w+)",
			"tree": { "group": "Docs" },
			"editor":
			[
				{
					"link": "${file}/docs/$1.md",
					"color": "#66D9EF",
					"hoverMessage": "View $1 Docs"
				}
			]
		}
	],
```

Thanks!

**Comment by dlevs** [comment]
Hi @ylazy,

That should be supported by Regex Robin: https://github.com/dlevs/vscode-regex-robin/blob/main/src/compileTemplate/templateArgs.ts#L66

Is the path definitely correct? If not, there are other variables that can be useful, like `fileDirname`. If the path does look right, maybe it's a Windows issues. I've only tested on MacOS

I'm going to close this as this conversation relates to a different repo, but feel free to reach out on that Regex Robin repository.

**Comment by dlevs** [comment]
This comment might help in case it _is_ a Windows issue: https://github.com/dlevs/vscode-regex-robin/issues/5#issuecomment-1880413812

**Comment by ylazy** [comment]
Sorry for the delay in responding,
I've updated Regex Robin today and the issue has been resolved.
Thank you so much!
